services:
  database:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: dashboard
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U test"]
      interval: 10s 
      timeout: 5s 
      retries: 5

  server:
    build:
      context: ./ 
      dockerfile: Dockerfile 
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure
