[server]
host = "127.0.0.1"
port = 8080
production = true
cors-url = "*"
jwt-secret = "testing"

[db]
username = "test"
password = "test"
host = "database"
port = 5432
ssl = false
dbname = "dashboard"
