[server]
host = "0.0.0.0"
port = 8080
production = false
cors-url = ["*"]
jwt-secret = "testing"
token-expiry = 10
totp-issuer = "V-NEST"

[db]
username = "test"
password = "test"
host = "database"
port = 5432
ssl = false
dbname = "dashboard"
